<a href="https://colab.research.google.com/github/brycemcwilliams/research-papers/blob/master/tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 75kB/s 
     |████████████████████████████████| 450kB 27.7MB/s 
     |████████████████████████████████| 3.8MB 39.4MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=2f96c5067f7c61bff2010312847dd2e8c8ba37e0f0c7672f15bddbf3502bdd87
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.10.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Found existing installation: t

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [4]:
a = 4 + 2j # complex number
b = 6 + 7j

c = a + b
d = tf.square(c)
print(a,b,c,d)

print(a-b)
print(a*b)

(4+2j) (6+7j) (10+9j) tf.Tensor((19+180j), shape=(), dtype=complex128)
(-2-5j)
(10+40j)


In [5]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print(c)

tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


In [6]:
import numpy as np
y = np.array([[1, 2, 2], [8, 2, 5]])

print(y)
# We can also convert a tensor into a numpy array by using .numpy()
c.numpy()

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

In [7]:
print('Tensor Data Type', c.dtype)
print('Tensor Shape', c.shape)
# You can notice the similarity with numpy 
# You can also call the different default tensors as you would do for numpy

Tensor Data Type <dtype: 'float32'>
Tensor Shape (2, 3)


In [8]:
c

<tf.Tensor: id=4, shape=(2, 3), dtype=float32, numpy=
array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)>

In [9]:
c.shape

TensorShape([2, 3])

In [11]:
tf.ones([3, 3], tf.int32)

<tf.Tensor: id=10, shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [12]:
tf.zeros([3, 3], tf.int32)

<tf.Tensor: id=13, shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [13]:
random_variable = tf.ones(shape = (3,3))
# random variable
tf_variable = tf.Variable(random_variable)
print(tf_variable)

# you can also update the values of your variable.
tf_variable.assign(tf.zeros(shape = (3,3)))
print(tf_variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


In [14]:
# computing derivative for the function 3x^2 at x = 3

x = tf.constant(3.0) # gradient at
with tf.GradientTape() as g:
  g.watch(x) # record the operations
  y = 3*x*x
dy_dx = g.gradient(y, x) 
print(dy_dx)


# you can also use nested GradientTape() for the second derivative
# computing second derivative for the function 4x^2 at x = 4.0

x = tf.constant(4.0)
with tf.GradientTape() as gt:
  gt.watch(x)
  with tf.GradientTape() as g:
    g.watch(x)  
    y = 4*x*x
  dy_dx = g.gradient(y, x)
d2y_dx2 = gt.gradient(dy_dx,x)
print(d2y_dx2)

tf.Tensor(18.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


In [17]:
x = tf.constant(1.0, shape=[3, 3])
print(x)
exp = tf.math.exp(x)
print(exp)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2.7182817 2.7182817 2.7182817]
 [2.7182817 2.7182817 2.7182817]
 [2.7182817 2.7182817 2.7182817]], shape=(3, 3), dtype=float32)


In [20]:
var = 2j
print(var)

2j


In [21]:
x = tf.Variable(tf.random.normal(shape=(3,2)))
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-1.6141663,  0.9079517],
       [ 0.5893458,  0.9616784],
       [ 1.9611958, -0.9466995]], dtype=float32)>

In [22]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-1.6141663,  0.9079517],
       [ 0.5893458,  0.9616784],
       [ 1.9611958, -0.9466995]], dtype=float32)>

In [23]:
# your code here
x.assign_sub(tf.ones(shape = (3,2)))

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[-2.6141663 , -0.09204829],
       [-0.4106542 , -0.03832161],
       [ 0.9611958 , -1.9466995 ]], dtype=float32)>

In [24]:
# your code here
x = tf.constant(1.0) 
with tf.GradientTape() as g:
  g.watch(x) 
  with tf.GradientTape() as g1:
    g1.watch(x) 
    with tf.GradientTape() as g2:
      g2.watch(x) 
      y = 4*x*x*x + x*x + 1
    dy_dx = g2.gradient(y, x)   
  d2y_dx2 = g1.gradient(dy_dx, x)
d3y_dx3 = g.gradient(d2y_dx2, x)

print(d3y_dx3)

tf.Tensor(24.0, shape=(), dtype=float32)


In [25]:
# your code here for dot product
a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
b = tf.constant([[1],[2],[3]])

c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[14]
 [32]
 [50]], shape=(3, 1), dtype=int32)


In [26]:
# your code here for element wise product
d = tf.multiply(a, b)
d

<tf.Tensor: id=149, shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]], dtype=int32)>